#include <furi.h>
#include "skylanders_nfc_data.h"

/* generated by fbt from .png files in images folder */
#include <skylanders_nfc_data_icons.h>

int32_t skylanders_nfc_data_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm skylanders_nfc_data!");

    return 0;
}
